# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(default=datetime.datetime(2017, 2, 11, 16, 9, 37, 800830, tzinfo=utc))),
            ],
        ),
    ]
