# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmsSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status_cpu', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_by', models.CharField(max_length=128)),
                ('memory', models.IntegerField()),
                ('localization', models.CharField(max_length=128)),
                ('baterry_per_cpu', models.IntegerField()),
                ('id_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CommunicationType')),
            ],
        ),
        migrations.CreateModel(
            name='CPUPerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CPU')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status_module', models.BooleanField(default=True)),
                ('baterry_per_module', models.IntegerField()),
                ('localization', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModulePerCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CPU')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsPerModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Module')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('magnitude', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorType'),
        ),
        migrations.AddField(
            model_name='reading',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor'),
        ),
        migrations.AddField(
            model_name='alarmssettings',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor'),
        ),
        migrations.AddField(
            model_name='alarms',
            name='id_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Reading'),
        ),
    ]
