# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='scale_value',
            field=models.CharField(max_length=255),
        ),
    ]
