# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 2, 11, 16, 18, 33, 977327, tzinfo=utc)),
        ),
    ]
