# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0002_auto_20170221_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunicationType',
        ),
    ]
