# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saliapp', '0003_delete_communicationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path_or_number', models.CharField(max_length=128)),
            ],
        ),
    ]
