# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0003_delete_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtype',
            name='image_path',
            field=models.CharField(default=-2017, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortype',
            name='image_path',
            field=models.CharField(default='path', max_length=128),
            preserve_default=False,
        ),
    ]
