# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0003_auto_20170212_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='Membership',
            new_name='SensorMeasurements',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='sensormeasurements',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Measure'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='measure',
            name='members',
            field=models.ManyToManyField(through='saliapp.SensorMeasurements', to='saliapp.Sensor'),
        ),
    ]
