# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0004_auto_20170307_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
