# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0004_auto_20170212_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='members',
        ),
        migrations.RemoveField(
            model_name='sensormeasurements',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sensormeasurements',
            name='person',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorMeasurements',
        ),
    ]
