# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0005_alarms_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='color',
            field=models.CharField(default=-1201, max_length=100),
            preserve_default=False,
        ),
    ]
