# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0005_controllermodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllermodule',
            name='id_by_create',
        ),
        migrations.RemoveField(
            model_name='controllermodule',
            name='id_communication',
        ),
        migrations.DeleteModel(
            name='ControllerModule',
        ),
    ]
