# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saliapp', '0006_auto_20170221_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status_cm', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('memory', models.IntegerField()),
                ('localization_cm', models.CharField(max_length=128)),
                ('baterry_cm', models.IntegerField()),
                ('id_by_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CommunicationType')),
            ],
        ),
    ]
