# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saliapp', '0007_controllermodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMPerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.ControllerModule')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
