# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saliapp', '0007_auto_20170212_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('coordination', models.CharField(max_length=128)),
                ('temperature', models.BigIntegerField()),
                ('salinity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2017, 2, 12, 16, 37, 59, 229938, tzinfo=utc))),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Measure')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='members',
            field=models.ManyToManyField(through='saliapp.SensorMeasurements', to='saliapp.Sensor'),
        ),
    ]
