# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0007_alarms_max_or_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarms',
            old_name='check',
            new_name='checked',
        ),
    ]
