# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0008_cmperusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('seding_time', models.IntegerField()),
                ('status_sm', models.BooleanField(default=True)),
                ('baterry_sm', models.IntegerField()),
                ('localization_sm', models.CharField(max_length=128)),
            ],
        ),
    ]
