# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0008_auto_20170212_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensormeasurements',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 2, 12, 19, 49, 48, 696659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sensormeasurements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
