# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import saliapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saliapp', '0008_auto_20170313_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_dev', models.CharField(default=saliapp.models.my_random_key, max_length=16)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
