# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0009_sensormodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTypePerSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_communication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CommunicationType')),
                ('id_sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.ControllerModule')),
            ],
        ),
        migrations.CreateModel(
            name='SMPerCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.ControllerModule')),
                ('id_sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorModule')),
            ],
        ),
    ]
