# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import saliapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0009_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkey',
            name='key_dev',
            field=models.CharField(default=saliapp.models.my_random_key, max_length=16, unique=True),
        ),
    ]
