# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0010_auto_20170322_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtype',
            name='image_path',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
