# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saliapp', '0010_auto_20170215_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('id_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CommunicationType')),
            ],
        ),
    ]
