# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0010_communicationtypepersm_smpercm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('scale_value', models.CharField(max_length=10)),
                ('status_actuator', models.BooleanField(default=False)),
            ],
        ),
    ]
