# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0011_sensortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorType')),
                ('id_sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorModule')),
            ],
        ),
    ]
