# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0011_auto_20170322_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='image_path',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
