# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0012_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id_sensor_type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='id_sm',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorType',
        ),
    ]
