# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0012_cpuperusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='id_communication',
        ),
        migrations.RemoveField(
            model_name='cpuperusers',
            name='id_cpu',
        ),
        migrations.RemoveField(
            model_name='cpuperusers',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='CommunicationType',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='CPUPerUsers',
        ),
    ]
