# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saliapp', '0013_auto_20170215_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('id_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CommunicationType')),
            ],
        ),
        migrations.CreateModel(
            name='CPUPerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CPU')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
