# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0013_auto_20170221_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_actuator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('scale_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorType'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_sm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorModule'),
        ),
    ]
