# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0014_auto_20170221_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmsSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max', models.FloatField(default=0.0)),
                ('min', models.FloatField(default=0.0)),
                ('msgMax', models.CharField(max_length=228)),
                ('msgMin', models.CharField(max_length=228)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
    ]
