# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0014_communicationtype_cpu_cpuperusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModulePerCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.CPU')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsPerModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Module')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('magnitude', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.SensorType'),
        ),
    ]
