# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0015_auto_20170215_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmsSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='alarms',
            name='id_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Reading'),
        ),
    ]
