# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0015_alarmssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Sensor')),
            ],
        ),
    ]
