# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saliapp', '0016_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saliapp.Reading')),
            ],
        ),
    ]
